backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/static/images"

locale: 'ar'

collections:
  - name: "posts"
    label: "المقالات"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "التصنيف", name: "category", widget: "select", options: ["هاتف", "سماعة", "لاب تاب", "ساعة", "أخبار"] }
      - { label: "التقييم (من 10)", name: "rating", widget: "number", min: 0, max: 10 }
      - { label: "الصورة الرئيسية", name: "image", widget: "image", required: false }
      - { label: "وصف قصير", name: "description", widget: "string" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
      - { label: "تاريخ النشر", name: "date", widget: "datetime" }
      - { label: "منشور؟", name: "published", widget: "boolean", default: true }
